name: Formatting

on:
  push:
    branches: [master]
    paths:
      - docs/**
  pull_request:
    branches: [master]
    paths:
      - docs/**

jobs:
  test:
    name: Check docs formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env:
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1
        with:
          ref: ${{ github.head_ref }}

      - name: Check formatting
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --write docs
